FROM node:16 AS build

# TODO: Set workdir

# TODO: Copy package.json to current workdir

# TODO: Run command to install packages

# TODO: Copy source code to current workdir

# TODO: Run tests or build tasks if needed

# TODO: Expose app port

# TODO: Run command to start the app
